name = "Elephants"
license = "MIT"
licenselink = "https://github.com/meibenny/elephants/blob/master/LICENSE.md"
description = "Minimal theme using the Ubuntu font."
homepage = "https://gitlab.com/meibenny/elephants"
tags = ["blog", "personal", "minimal"]
features = ["blog", "personal", "minimal", "no javascript", "high contrast"]
min_version = "0.57.2"

[author]
  name = "Benny Mei"
  homepage = "https://gitlab.com/meibenny/elephants"
